name: Build
# testing sample DevOps with Git workflow
on:
  push:
    branches:
      - main  # Modify this to match your repository's main branch
  pull_request:
    branches: [ "main" ]    

 

jobs:
  scan:
    runs-on: ubuntu-latest
    uses: PonSwaetha/reusable@main

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 
