name: Build
# testing sample DevOps with Git workflow
on:
  push:
    branches:
      - main  # Modify this to match your repository's main branch
  pull_request:
    branches: [ "main" ]    

 

jobs:
  call-workflow:
    uses: PonSwaetha/reusable/.github/workflows/main.yml@main

 

    

 
