name: Build
# testing sample DevOps with Git workflow
on:
  push:
    branches:
      - main  # Modify this to match your repository's main branch
  pull_request:
    branches: [ "main" ]    

 

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Scanning
      uses: PonSwaetha/reusable/.github/workflows/main.yml@main

 

    

 
